Fix compilation error: /boot/home/openbeos-cvs/stable/src/add-ons/kernel/network/ppp/shared/libkernelppp/KPPPLCP.cpp: In method `status_t PPPLCP::Receive(struct mbuf *, short unsigned int)': /boot/home/openbeos-cvs/stable/src/add-ons/kernel/network/ppp/shared/libkernelppp/KPPPLCP.cpp:221: implicit declaration of function `int printf(...)'
{We're in kernel land now, so we use dprintf instead of printf}


git-svn-id: http://svn.haiku-os.org/haiku/trunk/current@5940 a95241bf-73f2-0310-859d-f6bbb57e9c96